-- MySQL Script generated by MySQL Workbench
-- Thu Jul 26 13:43:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema protocolo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema protocolo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `protocolo` DEFAULT CHARACTER SET utf8 ;
USE `protocolo` ;

-- -----------------------------------------------------
-- Table `protocolo`.`Protocolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `protocolo`.`Protocolo` ;

CREATE TABLE IF NOT EXISTS `protocolo`.`Protocolo` (
  `idProtocolo` INT NOT NULL AUTO_INCREMENT,
  `cod` INT NULL,
  `tipo` INT NULL,
  `data` DATETIME NULL,
  `certidao` TINYINT NULL,
  `peticao` TINYINT NULL,
  `escritura` TINYINT NULL,
  `inventariado` VARCHAR(400) NULL,
  `advogado` VARCHAR(300) NULL,
  `valor` DOUBLE NULL,
  `paralizado` TINYINT NULL,
  `documentos` TINYINT NULL,
  `itcd` TINYINT NULL,
  `dae` TINYINT NULL,
  `certQuitacao` TINYINT NULL,
  `certNegativa` TINYINT NULL,
  `textoPronto` TINYINT NULL,
  `assinaturas` TINYINT NULL,
  `pronto` TINYINT NULL,
  PRIMARY KEY (`idProtocolo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
